---
- name: "REMEDIATE: Install ClamSAP package when enabled"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  become: true
  loop: "{{ clamsap_package_names }}"
  when:
    - enable_package_remediation | bool

- name: "REMEDIATE: Install Watchman package when enabled"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  become: true
  loop: "{{ watchman_package_names }}"
  when:
    - enable_package_remediation | bool
